package automationFramework.Utilities;

public class Global {

	// Run lab server
	//public static final String URL1 = "http://172.23.4.196:9001/#/main/admin";
	//public static final String URL2 = "http://172.23.4.196:9001";
	public static final String URL3 = "http://172.23.4.196:8701/cms/status";
	
	// Run PIL server
	public static final String URL1 = "http://10.252.1.131:9001/#/main";
	public static final String URL2 = "http://10.252.1.131:9001/#/";

	// Run local machine
	// public static final String URL1 = "http://localhost:9001/#/main/admin";
	// public static final String URL2 = "http://localhost:9001";

	public static final String OS = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\ProductName";
	public static final String USER = "Admin";
	public static final String PASSWD = "password";
	public static final String CC = "4916997583130747";
	public static final String CC2 = "4012888888881881";
	public static final String CCMASKED = "************0747";
	public static final String CCMASKED2 = "************1881";
	public static final String CCTYPE = "Visa";
	public static final String EXPDATE = "05 - May";
	public static final String EXPYEAR = "2019";
	public static final String PAYMENT = "Visa - 0747";
	public static final String CVV = "111";
	public static final String CODE = "250";
	public static final String PIN = "1234";
	public static final String MAILINATOR = "@mailinator.com";
	public static final String EMAIL = "rbdownton@yahoo.com";
	public static final String MESSAGE = "test";
	public static final String FNAME = "robert";
	public static final String FULLNAME = "robert downton";
	public static final String FNAME2 = "indy";
	public static final String LNAME = "downton";
	public static final String LNAME2 = "jones";
	public static final String EXISTING_USER = "test1234";
	public static final String NICKNAME = "rocky";
	public static final String CCNAME = "charles carson";
	public static final String CCNAME2 = "emma thompson";
	public static final String PHONE = "8588885558";
	public static final String PHONE2 = "9998889999";
	public static final String ADDRESS = "123 broadway";
	public static final String COMPLETE_ADDRESS = "123 broadway, san diego, CA, 92122, USA";
	public static final String NEWADDRESS = "200 market";
	public static final String POSTAL = "92122";
	public static final String NEWPOSTAL = "92123";
	public static final String CITY = "san diego";
	public static final String NEWCITY = "la Jolla";
	public static final String STATE = "CA";
	public static final String NEWSTATE = "CA";
	public static final String PHONETYPE = "M";
	public static final String DOB = "1987-05-17";
	public static final String USERNAME = "Admintest1";
	public static final String CONTACTTYPE = "Primary";
	public static final String CUSTOMERTYPE = "Individual";
	public static final String SECURITYA = "forty";
	public static final String LOG_FILE = "C://Automation//Logs//logfile.log";
	public static final String Path_TestData = "C://Automation//Data//";
	public static final String File_TestData = "TestData.xlsx";
	public static final String CHAR_LIST = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMONOPQRSTUWXYZ1234567890";
	public static final String MONGO = "172.23.4.198";
	public static final String DB = "test";
	public static final String COLLECTION = "user";
	public static final String POSTGRESDB = "jdbc:postgresql://172.23.4.198:5432/test";
	public static final String POSTGRESUSER = "testuser";
	public static final String POSTGRESPASS = "postgres";
	public static final String KEYCLOAKUSER = "ray";
	public static final String KEYCLOAKPASS = "sandiego101";
	public static final String DUPLICATE_ERROR = "UserName has duplicate value. Value must be unique. Please enter a different value.";
	public static final String INVALID_EMAIL = "Invalid email address.";
	public static final String BAD_PIN = "111";
	public static final String PIN_ERROR = "Minimum length should be 4";
	public static final String PIN_ERROR2 = "errors.pin.cannot.contain.username";
	public static final String CC_ERROR = "Card Number is invalid.";
	public static final String INVALID_CC = "491699758313074";
	public static final String USERNAME_ERROR = "Invalid Format.";
	public static final String REQUIREDFIELD_ERROR = "This is a required field.";
	public static final String INVALID_PHONE = "4916";
	public static final String PURSE = "Stored Value";
	public static final String PURSE2 = "Default Purse";
	public static final String ENTRY_TYPE = "Load Value";
	public static final String ENTRY_TYPE2 = "Purse Load";
	public static final String TOKEN_DATA = "4386911579322359=17011010000067200000";
	public static final String ABP_SERVER = "172.23.4.200";
	public static final String INPUT_FILE = "C://Automation/Data/tokenData.txt";
	public static final String INDEX_FILE = "C://Automation/Data/index.txt";
	public static final String NEW_FULLADDRESS = "200 market, la Jolla, CA, 92123, USA";
	public static final String FULLADDRESS = "123 broadway, san diego, CA, 92122, USA";
	public static final String INVALID_DATA = "$$$$$%%%%%";
	public static final String INVALID_EMAIL_ERROR = "Invalid email address.";
	public static final String INVALID_FORMAT_ERROR = "Invalid Format.";
	public static final String MIN_LENGTH_ERROR = "Minimum length should be 4";
	public static final String UNEXPECTED_ERROR = "An unexpected system error has occurred. Please contact your administrator.";
	public static final String PAN_ERROR = "Card Number is too long.";
	public static final String PAN_ERROR2 = "Card Number does not match with credit card type.";
	public static final String PAN_ERROR3 = "Card Expiration errors.credit.card.expiration.date.must.not.be.past.date";
	public static final String UNREGISTRED_ACCOUNT = "440000001626";
	public static final String REGISTRED_ACCOUNT = "5582619509951283";
	public static final String AUTHENTICATION_ERROR = "errors.authentication.token.invalid";
	public static final String POSTALCODE_SEARCH_ERROR = "Search by postal code alone is not allowed.";
	public static final String POSTAL_ERROR = "Zip Code is invalid.";
	public static final String ADDRESS_ERROR = "The address entered already exists.Please try again.";
	public static final String PHONE_ERROR = "phone[0].number errors.general.invalid.phone.number";
	public static final String CONFIG = "http://172.23.4.196:8201/nis/config";
	public static final String DATE_PICKER_DISPLAY =  "display: block; visibility: visible; top: 28px; left: 0px; z-index: 1003;";
}
